#!/bin/bash

if [ "$#" -eq 3 ]; then 
    echo "Running Bison ..."
    yacc -d -y --debug --verbose $1
    echo 'Generated the parser C file as well the header file'
    echo "Running g++ on the C file generated by Bison ..."
    g++ -w -c -o y.o y.tab.c
    echo 'Generated the parser object file'
    echo "Running Flex ..."
    flex $2
    echo 'Generated the scanner C file'
    echo "Running g++ on the C file generated by Flex ..."
    g++ -fpermissive -w -c -o l.o lex.yy.c
    echo 'Generated the scanner object file'
    echo "Running g++ on both the generated generated syntax and lexical analyzer ..."
    g++ -g y.o l.o
    echo 'All ready, running'
    ./a.out $3
    echo 'logfile generated'
    #cat $3
elif [[ "$#" -eq 1 && "$1" -eq 'rm' ]]; then
    echo "Removing generated files ..."
    rm y.o y.tab.c l.o lex.yy.c y.tab.h y.output a.out 21141013_log.txt 21141013_error.txt
    echo "Generated files removed"
else
    echo "./script.sh <file.y> <file.l> <input_file_name.c>"
fi

